name: GitHub Pages Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: sudo npm i -g csso-cli terser html-minifier

      - name: Update Cache
        run: sed -i 's/^const version.*$/const version="'"$GITHUB_RUN_ID"'"/' service-worker.js

      - name: Use minified files
        run: sed -i 's/item-finder.js/item-finder.min.js/; s/service-worker.js/service-worker.min.js/; s/item-finder.css/item-finder.min.css/' index.html service-worker.js

      - name: Minify Javascript
        run: |
          terser item-finder.js -c unsafe=true -m "properties=true, toplevel=true, reserved=['csv_string', 'file_opened', 'filter_table', 'download_as_csv']" --source-map --output item-finder.min.js
          terser service-worker.js --source-map --output service-worker.min.js

      - name: Minify CSS
        run: csso item-finder.css --source-map file --output item-finder.min.css

      - name: Minify HTML
        run: html-minifier index.html --collapse-boolean-attributes --collapse-inline-tag-whitespace --collapse-whitespace --conservative-collapse --decode-entities --html5 --include-auto-generated-tags --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes -o index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
