name: Build and Deploy to GitHub Pages

# Stardew Valley Item Finder
# https://gucci-on-fleek.github.io/Stardew-Valley-Item-Finder/
# Licensed under MPL 2.0 or greater. See URL for more information.

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # We could use a proper build system to build the website,
      # but most of the "proper" HTML/JS build systems are overkill
      # for a small, single-file web app. Instead, we will minify
      # each file, then combine them by (ab)using `sed`.
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Run build script
        run: ./build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.5.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
