name: Build and Deploy to GitHub Pages

# Stardew Valley Item Finder
# https://gucci-on-fleek.github.io/Stardew-Valley-Item-Finder/
# Licensed under MPL 2.0 or greater. See URL for more information.

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # We could use a proper build system to build the website,
      # but most of the "proper" HTML/JS build systems are overkill
      # for a small, single-file web app. Instead, we will minify
      # each file, then combine them by (ab)using `sed`.
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          sudo npm i -g csso-cli terser html-minifier # csso to minify CSS, terser to minify JS, and html-minifier to minify HTML
          sudo apt install minify # to minify the XSLT

      - name: Update Cache
        run: sed -i 's/^const version.*$/const version="'"$GITHUB_RUN_ID"'"/' service-worker.js # The service worker will only update the cache if its version is changed

      - name: Use minified files
        run: sed -i 's/item-finder.js/item-finder.min.js/; s/service-worker.js/service-worker.min.js/; s/item-finder.css/item-finder.min.css/; s/items.xslt/items.min.xslt/; s/items-to-csv.xslt/items-to-csv.min.xslt/' index.html service-worker.js item-finder.js

      - name: Minify Javascript
        run: |
          terser item-finder.js -c unsafe=true -m "toplevel=true, reserved=['csv_string', 'file_opened', 'filter_table', 'download_as_csv']" --mangle-props 'regex = /template/' --source-map "url=item-finder.min.js.map" --output item-finder.min.js
          terser service-worker.js --source-map "url=service-worker.min.js.map" --output service-worker.min.js

      - name: Minify CSS
        run: csso item-finder.css --source-map file --output item-finder.min.css

      - name: Minify XSLT
        run: |
          minify --type=xml -o items.min.xslt items.xslt
          minify --type=xml -o items-to-csv.min.xslt items-to-csv.xslt

      - name: Inline JavaScript and CSS
        run: |
          sed -i '/<script src="item-finder.min.js">/r item-finder.min.js' index.html # Insert the contents of ---.js after the opening script tag
          sed -i '/<script src="libraries\/tablesort.min.js" async>/r libraries/tablesort.min.js' index.html
          sed -i 's/<link rel="stylesheet" href="item-finder.min.css" \/>/<style>\n<\/style>/' index.html # Replace the stylesheet link with a blank style element
          sed -i '/<style>/r item-finder.min.css' index.html # Now insert the style into the style element
          sed -i 's/script src=".*"\( async\)\?/script/' index.html # Remove the src attribute from the script tags
          sed -i 's/"\(tablesort\|item-finder\)\.min\.\(js\|css\)",\?//g' service-worker.min.js # Remove the files from the cache since they're inlined

      - name: Minify HTML
        run: html-minifier index.html --collapse-boolean-attributes --collapse-inline-tag-whitespace --collapse-whitespace --conservative-collapse --decode-entities --html5 --include-auto-generated-tags --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes -o index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.5.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
